Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "ubuntu14",
          :box => "bento/ubuntu-14.04",
          :ip => "192.168.50.4",
          :ssh_port => '12200'
        },
        {
          :hostname => "ubuntu16",
          :box => "bento/ubuntu-16.04",
          :ip => "192.168.50.5",
          :ssh_port => '13200'
        },
        {
          :hostname => "freebsd12",
          :box => "bento/freebsd-12.2",
          :ip => "192.168.50.6",
          :ssh_port => '14200'
        },
        {
          :hostname => "trusty32",
          :box => "ubuntu/trusty32",
          :ip => "192.168.50.8",
          :ssh_port => '16200'
        }
    ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provider :virtualbox do |vb|
                vb.gui = true
                vb.customize ["modifyvm", :id, "--memory", 1024]
                vb.customize ["modifyvm", :id, "--cpus", 1]
            end
        end
    end
end